language: node_js
node_js:
  - "13.12.0"
cache:
  directories:
    - node_modules
script:
  - npm test
  - CI=false npm run build
notifications:
  email:
    recipients:
      - patricelouise15@gmail.com
    on_success: always
    on_failure: always
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive